/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Sara
 */
public class VentanaBuscar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaBuscar
     */
    public VentanaBuscar() {
        setTitle("Consultar Estado Militar");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buscar = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        bReservista1 = new javax.swing.JRadioButton();
        bRemiso1 = new javax.swing.JRadioButton();
        bMenorEdad = new javax.swing.JRadioButton();
        bRecluta = new javax.swing.JRadioButton();
        bAplazado1 = new javax.swing.JRadioButton();
        textoCedula1 = new javax.swing.JLabel();
        textoNombre1 = new javax.swing.JLabel();
        textoApellido1 = new javax.swing.JLabel();
        textoEdad1 = new javax.swing.JLabel();
        textoLibreta1 = new javax.swing.JLabel();
        textoFecha1 = new javax.swing.JLabel();
        cajaCedula1 = new javax.swing.JTextField();
        cajaNombre1 = new javax.swing.JTextField();
        cajaApellido1 = new javax.swing.JTextField();
        cajaEdad1 = new javax.swing.JTextField();
        cajaLibreta1 = new javax.swing.JTextField();
        cajaFecha1 = new javax.swing.JTextField();
        btnConsultar2 = new javax.swing.JButton();
        btnLimpiar1 = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        Buscar.add(bReservista1);
        bReservista1.setText("Reservista");

        Buscar.add(bRemiso1);
        bRemiso1.setText("Remiso");

        Buscar.add(bMenorEdad);
        bMenorEdad.setText("Menor de edad");
        bMenorEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenorEdadActionPerformed(evt);
            }
        });

        Buscar.add(bRecluta);
        bRecluta.setText("Recluta");

        Buscar.add(bAplazado1);
        bAplazado1.setText("Aplazado");

        textoCedula1.setText("Cédula");

        textoNombre1.setText("Nombre");

        textoApellido1.setText("Apellido");

        textoEdad1.setText("Edad");

        textoLibreta1.setText("Libreta Militar o Código de Reclutamiento");

        textoFecha1.setText("Fecha de Aplazamiento");

        cajaCedula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCedula1ActionPerformed(evt);
            }
        });

        cajaNombre1.setEditable(false);

        cajaApellido1.setEditable(false);

        cajaEdad1.setEditable(false);

        cajaLibreta1.setEditable(false);

        cajaFecha1.setEditable(false);

        btnConsultar2.setText("Consultar");

        btnLimpiar1.setText("Limpiar");
        btnLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar1ActionPerformed(evt);
            }
        });

        btnSalir1.setText("Salir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(bRecluta)
                        .addGap(73, 73, 73)
                        .addComponent(bAplazado1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoCedula1)
                                    .addComponent(textoFecha1)
                                    .addComponent(textoLibreta1)
                                    .addComponent(textoEdad1)
                                    .addComponent(textoApellido1)
                                    .addComponent(textoNombre1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cajaCedula1)
                                    .addComponent(cajaNombre1)
                                    .addComponent(cajaApellido1)
                                    .addComponent(cajaEdad1)
                                    .addComponent(cajaLibreta1)
                                    .addComponent(cajaFecha1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bReservista1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bRemiso1)
                                .addGap(85, 85, 85)
                                .addComponent(bMenorEdad)))
                        .addGap(29, 29, 29))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnLimpiar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir1)
                .addGap(96, 96, 96))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(btnConsultar2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bReservista1)
                    .addComponent(bRemiso1)
                    .addComponent(bMenorEdad))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRecluta)
                    .addComponent(bAplazado1))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCedula1)
                    .addComponent(cajaCedula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNombre1)
                    .addComponent(cajaNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoApellido1)
                    .addComponent(cajaApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoEdad1)
                    .addComponent(cajaEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoLibreta1)
                    .addComponent(cajaLibreta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoFecha1)
                    .addComponent(cajaFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConsultar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar1)
                    .addComponent(btnSalir1))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bMenorEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenorEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bMenorEdadActionPerformed

    private void cajaCedula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCedula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaCedula1ActionPerformed

    private void btnLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBuscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Buscar;
    private javax.swing.JRadioButton bAplazado1;
    private javax.swing.JRadioButton bMenorEdad;
    private javax.swing.JRadioButton bRecluta;
    private javax.swing.JRadioButton bRemiso1;
    private javax.swing.JRadioButton bReservista1;
    public javax.swing.JButton btnConsultar2;
    public javax.swing.JButton btnLimpiar1;
    public javax.swing.JButton btnSalir1;
    private javax.swing.JTextField cajaApellido1;
    private javax.swing.JTextField cajaCedula1;
    private javax.swing.JTextField cajaEdad1;
    private javax.swing.JTextField cajaFecha1;
    private javax.swing.JTextField cajaLibreta1;
    private javax.swing.JTextField cajaNombre1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textoApellido1;
    private javax.swing.JLabel textoCedula1;
    private javax.swing.JLabel textoEdad1;
    private javax.swing.JLabel textoFecha1;
    private javax.swing.JLabel textoLibreta1;
    private javax.swing.JLabel textoNombre1;
    // End of variables declaration//GEN-END:variables

    //Metodo para limpiar el campo de cédula
    public void limpiarCampo(){
        cajaCedula1.setText("");
    }
}

