/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author Sara
 */
public class VentanaBuscar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaBuscar
     */
    public VentanaBuscar() {
        setTitle("Consultar Estado Militar");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buscar = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        bReservista1 = new javax.swing.JRadioButton();
        bRemiso1 = new javax.swing.JRadioButton();
        bMenorEdad1 = new javax.swing.JRadioButton();
        bRecluta1 = new javax.swing.JRadioButton();
        bAplazado1 = new javax.swing.JRadioButton();
        textoCedula1 = new javax.swing.JLabel();
        textoNombre1 = new javax.swing.JLabel();
        textoApellido1 = new javax.swing.JLabel();
        textoEdad1 = new javax.swing.JLabel();
        textoLibreta1 = new javax.swing.JLabel();
        textoFecha1 = new javax.swing.JLabel();
        cajaCedula1 = new javax.swing.JTextField();
        cajaNombre1 = new javax.swing.JTextField();
        cajaApellido1 = new javax.swing.JTextField();
        cajaEdad1 = new javax.swing.JTextField();
        cajaLibreta1 = new javax.swing.JTextField();
        cajaFecha1 = new javax.swing.JTextField();
        btnConsultar2 = new javax.swing.JButton();
        btnLimpiar1 = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        bVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buscar.add(bReservista1);
        bReservista1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bReservista1.setForeground(new java.awt.Color(255, 255, 255));
        bReservista1.setText("Reservista");
        bReservista1.setContentAreaFilled(false);
        jPanel1.add(bReservista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        Buscar.add(bRemiso1);
        bRemiso1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bRemiso1.setForeground(new java.awt.Color(255, 255, 255));
        bRemiso1.setText("Remiso");
        bRemiso1.setContentAreaFilled(false);
        jPanel1.add(bRemiso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        Buscar.add(bMenorEdad1);
        bMenorEdad1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bMenorEdad1.setForeground(new java.awt.Color(255, 255, 255));
        bMenorEdad1.setText("Menor de edad");
        bMenorEdad1.setContentAreaFilled(false);
        jPanel1.add(bMenorEdad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        Buscar.add(bRecluta1);
        bRecluta1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bRecluta1.setForeground(new java.awt.Color(255, 255, 255));
        bRecluta1.setText("Recluta");
        bRecluta1.setContentAreaFilled(false);
        jPanel1.add(bRecluta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        Buscar.add(bAplazado1);
        bAplazado1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bAplazado1.setForeground(new java.awt.Color(255, 255, 255));
        bAplazado1.setText("Aplazado");
        bAplazado1.setContentAreaFilled(false);
        jPanel1.add(bAplazado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        textoCedula1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        textoCedula1.setForeground(new java.awt.Color(255, 255, 255));
        textoCedula1.setText("Cédula");
        jPanel1.add(textoCedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        textoNombre1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        textoNombre1.setForeground(new java.awt.Color(255, 255, 255));
        textoNombre1.setText("Nombre");
        jPanel1.add(textoNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        textoApellido1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        textoApellido1.setForeground(new java.awt.Color(255, 255, 255));
        textoApellido1.setText("Apellido");
        jPanel1.add(textoApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        textoEdad1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        textoEdad1.setForeground(new java.awt.Color(255, 255, 255));
        textoEdad1.setText("Edad");
        jPanel1.add(textoEdad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        textoLibreta1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        textoLibreta1.setForeground(new java.awt.Color(255, 255, 255));
        textoLibreta1.setText("Libreta Militar o Código de Reclutamiento");
        jPanel1.add(textoLibreta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        textoFecha1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        textoFecha1.setForeground(new java.awt.Color(255, 255, 255));
        textoFecha1.setText("Fecha de Aplazamiento");
        jPanel1.add(textoFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));
        jPanel1.add(cajaCedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 150, -1));

        cajaNombre1.setEditable(false);
        jPanel1.add(cajaNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 150, -1));

        cajaApellido1.setEditable(false);
        jPanel1.add(cajaApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 150, -1));

        cajaEdad1.setEditable(false);
        jPanel1.add(cajaEdad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 150, -1));

        cajaLibreta1.setEditable(false);
        jPanel1.add(cajaLibreta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 150, -1));

        cajaFecha1.setEditable(false);
        jPanel1.add(cajaFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 150, -1));

        btnConsultar2.setBackground(new java.awt.Color(153, 255, 153));
        btnConsultar2.setText("Consultar");
        btnConsultar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        btnLimpiar1.setBackground(new java.awt.Color(153, 255, 153));
        btnLimpiar1.setText("Limpiar");
        jPanel1.add(btnLimpiar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));

        btnSalir1.setBackground(new java.awt.Color(153, 255, 153));
        btnSalir1.setText("Salir");
        jPanel1.add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        bVolver.setBackground(new java.awt.Color(153, 255, 153));
        bVolver.setText("Volver");
        jPanel1.add(bVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/fondobuscar.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultar2ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Buscar;
    public javax.swing.JRadioButton bAplazado1;
    public javax.swing.JRadioButton bMenorEdad1;
    public javax.swing.JRadioButton bRecluta1;
    public javax.swing.JRadioButton bRemiso1;
    public javax.swing.JRadioButton bReservista1;
    public javax.swing.JButton bVolver;
    public javax.swing.JButton btnConsultar2;
    public javax.swing.JButton btnLimpiar1;
    public javax.swing.JButton btnSalir1;
    public javax.swing.JTextField cajaApellido1;
    public javax.swing.JTextField cajaCedula1;
    public javax.swing.JTextField cajaEdad1;
    public javax.swing.JTextField cajaFecha1;
    public javax.swing.JTextField cajaLibreta1;
    public javax.swing.JTextField cajaNombre1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textoApellido1;
    private javax.swing.JLabel textoCedula1;
    private javax.swing.JLabel textoEdad1;
    private javax.swing.JLabel textoFecha1;
    private javax.swing.JLabel textoLibreta1;
    private javax.swing.JLabel textoNombre1;
    // End of variables declaration//GEN-END:variables

    //Metodo para limpiar el campo de cédula
    public void limpiarCampo(){
        cajaCedula1.setText("");
        cajaNombre1.setText("");
        cajaEdad1.setText("");
        cajaApellido1.setText("");
        cajaLibreta1.setText("");
        cajaFecha1.setText("");
    }
    public void cedulaVacia(){
        JOptionPane.showMessageDialog(null, "No hay cedula que consultar", "CAMPO CEDULA VACIO", JOptionPane.ERROR_MESSAGE);
    }
    public void radiosVacios(){
        JOptionPane.showMessageDialog(null, "Para consultar una persona, escoja su situacion militar", "SITUACION MILITAR SIN SELECCIONAR", JOptionPane.ERROR_MESSAGE);
    }

    public void listaVacia(String cadena){
        JOptionPane.showMessageDialog(null, "No hay " +cadena+" para consultar", "NO HAY PERSONAS EN EL SISTEMAS", JOptionPane.ERROR_MESSAGE);
    }

    public void personaNoExiste(){
        JOptionPane.showMessageDialog(null, "Esta persona no esta en la base de datos", "NO EXISTE", JOptionPane.ERROR_MESSAGE);
    }

    public void tieneOtraSituacion(){
        JOptionPane.showMessageDialog(null, "Esta persona no tiene la situacion militar seleccionada", "SITUACION MILITAR NO COINCEDENTE", JOptionPane.ERROR_MESSAGE);
    }
}

